# Generated by Django 4.2 on 2023-04-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('password', models.CharField(max_length=36, verbose_name='密码')),
                ('gender', models.SmallIntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别')),
                ('phone', models.CharField(max_length=12, verbose_name='电话')),
                ('integral', models.IntegerField(default=0, verbose_name='积分')),
            ],
        ),
    ]
