# Generated by Django 4.2 on 2023-04-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='integral',
            field=models.IntegerField(verbose_name='积分'),
        ),
    ]
