# Generated by Django 4.2 on 2023-04-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0002_rename_name_user_username_alter_user_integral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('imgURL', models.URLField()),
            ],
        ),
    ]
