# Generated by Django 4.2 on 2023-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0003_imgsave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgsave',
            name='imgURL',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
