# Generated by Django 4.2 on 2023-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testing', '0005_alter_imgsave_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgsave',
            name='imgURL',
            field=models.ImageField(upload_to=''),
        ),
    ]
