# Generated by Django 4.2 on 2023-04-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('role', models.SmallIntegerField(choices=[('0', '超管'), ('1', '商家'), ('2', '商家')])),
            ],
        ),
    ]
