# Generated by Django 4.2 on 2023-04-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_url',
            field=models.ImageField(upload_to='notices'),
        ),
    ]
