# Generated by Django 4.2 on 2023-04-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0003_alter_notice_description_alter_notice_notice_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice_url',
            new_name='img_url',
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
