# Generated by Django 4.2 on 2023-04-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0004_rename_notice_url_notice_img_url_alter_notice_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='img_url',
            new_name='imgURL',
        ),
    ]
