# Generated by Django 4.2 on 2023-04-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0005_rename_img_url_notice_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='imgURL',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='pub_date',
        ),
    ]
