# Generated by Django 4.2 on 2023-04-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0006_remove_notice_description_remove_notice_imgurl_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
