# Generated by Django 4.2 on 2023-04-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0008_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='imgURL',
            new_name='notice_url',
        ),
    ]
