# Generated by Django 4.2 on 2023-04-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0009_rename_imgurl_notice_notice_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='notice_url',
            new_name='imgURL',
        ),
    ]
