# Generated by Django 4.2 on 2023-04-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0011_remove_notice_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='imgURL',
            field=models.URLField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
