# Generated by Django 4.2 on 2023-04-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0012_notice_imgurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='imgURL',
            field=models.URLField(blank=True, default='https://tse4-mm.cn.bing.net/th/id/OIP-C.6LnWeT1-ui_FebxuImadCwHaFj?w=226&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7', max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dish_desc', models.TextField()),
                ('dish_img', models.ImageField(upload_to='dishes')),
                ('order_count', models.IntegerField(default=0)),
                ('dish_flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackstageApi.dishflavor')),
                ('dish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackstageApi.dishtype')),
            ],
        ),
    ]
