# Generated by Django 4.2 on 2023-04-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0013_dishflavor_dishtype_alter_notice_imgurl_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishflavor',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dishtype',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_flavor',
            field=models.ForeignKey(on_delete=models.SET('正常'), to='BackstageApi.dishflavor'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_type',
            field=models.ForeignKey(on_delete=models.SET('炒菜'), to='BackstageApi.dishtype'),
        ),
    ]
