# Generated by Django 4.2 on 2023-04-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0015_alter_dish_dish_flavor_alter_dish_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_img',
            field=models.URLField(max_length=300),
        ),
    ]
