# Generated by Django 4.2 on 2023-04-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ForegroundApi', '0006_user_email'),
        ('BackstageApi', '0016_alter_dish_dish_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('flavor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackstageApi.dishflavor')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ForegroundApi.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
                ('dish_total_price', models.FloatField()),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackstageApi.dish')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackstageApi.order')),
            ],
        ),
    ]
