# Generated by Django 4.2 on 2023-04-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0017_order_orderinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_flavor',
        ),
    ]
