# Generated by Django 4.2 on 2023-04-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0018_remove_dish_dish_flavor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_id',
            new_name='order',
        ),
    ]
