# Generated by Django 4.2 on 2023-04-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0019_rename_dish_id_orderinfo_dish_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='flavor_id',
            new_name='flavor',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='userid',
            new_name='user',
        ),
    ]
