# Generated by Django 4.2 on 2023-04-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0020_rename_flavor_id_order_flavor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
