# Generated by Django 4.2 on 2023-04-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackstageApi', '0021_admin_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='price',
            field=models.IntegerField(),
        ),
    ]
