# Generated by Django 5.0.1 on 2025-06-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackstageApi", "0022_alter_order_total_alter_orderinfo_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "待支付"),
                    ("paid", "已支付"),
                    ("accepted", "已接单"),
                    ("rejected", "已拒绝"),
                    ("completed", "已完成"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
