# Generated by Django 4.2 on 2023-04-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForegroundApi', '0003_remove_user_integral_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
