# Generated by Django 4.2 on 2023-04-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForegroundApi', '0005_user_gender_user_integral_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='123test@qq.com', max_length=254),
        ),
    ]
