# Generated by Django 4.2 on 2023-04-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ForegroundApi', '0006_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
