# Generated by Django 4.2 on 2023-04-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForegroundApi', '0007_delete_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='http://127.0.0.1:8000/media/dishes/f.png', verbose_name='用户头像'),
        ),
    ]
