# Generated by Django 4.2 on 2023-04-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForegroundApi', '0008_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='http://127.0.0.1:8000/media/users/avatar.jpg', verbose_name='用户头像'),
        ),
    ]
