# Generated by Django 5.0.1 on 2025-06-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ForegroundApi", "0009_alter_user_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="addr",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="收货地址"
            ),
        ),
    ]
